//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityInitParameters) DeepCopyInto(out *CapacityInitParameters) {
	*out = *in
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityInitParameters.
func (in *CapacityInitParameters) DeepCopy() *CapacityInitParameters {
	if in == nil {
		return nil
	}
	out := new(CapacityInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityObservation) DeepCopyInto(out *CapacityObservation) {
	*out = *in
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityObservation.
func (in *CapacityObservation) DeepCopy() *CapacityObservation {
	if in == nil {
		return nil
	}
	out := new(CapacityObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityParameters) DeepCopyInto(out *CapacityParameters) {
	*out = *in
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityParameters.
func (in *CapacityParameters) DeepCopy() *CapacityParameters {
	if in == nil {
		return nil
	}
	out := new(CapacityParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateFiltersInitParameters) DeepCopyInto(out *CertificateFiltersInitParameters) {
	*out = *in
	if in.CommonName != nil {
		in, out := &in.CommonName, &out.CommonName
		*out = new(string)
		**out = **in
	}
	if in.Organization != nil {
		in, out := &in.Organization, &out.Organization
		*out = new(string)
		**out = **in
	}
	if in.OrganizationalUnit != nil {
		in, out := &in.OrganizationalUnit, &out.OrganizationalUnit
		*out = new(string)
		**out = **in
	}
	if in.SubjectAlternativeName != nil {
		in, out := &in.SubjectAlternativeName, &out.SubjectAlternativeName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateFiltersInitParameters.
func (in *CertificateFiltersInitParameters) DeepCopy() *CertificateFiltersInitParameters {
	if in == nil {
		return nil
	}
	out := new(CertificateFiltersInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateFiltersObservation) DeepCopyInto(out *CertificateFiltersObservation) {
	*out = *in
	if in.CommonName != nil {
		in, out := &in.CommonName, &out.CommonName
		*out = new(string)
		**out = **in
	}
	if in.Organization != nil {
		in, out := &in.Organization, &out.Organization
		*out = new(string)
		**out = **in
	}
	if in.OrganizationalUnit != nil {
		in, out := &in.OrganizationalUnit, &out.OrganizationalUnit
		*out = new(string)
		**out = **in
	}
	if in.SubjectAlternativeName != nil {
		in, out := &in.SubjectAlternativeName, &out.SubjectAlternativeName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateFiltersObservation.
func (in *CertificateFiltersObservation) DeepCopy() *CertificateFiltersObservation {
	if in == nil {
		return nil
	}
	out := new(CertificateFiltersObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateFiltersParameters) DeepCopyInto(out *CertificateFiltersParameters) {
	*out = *in
	if in.CommonName != nil {
		in, out := &in.CommonName, &out.CommonName
		*out = new(string)
		**out = **in
	}
	if in.Organization != nil {
		in, out := &in.Organization, &out.Organization
		*out = new(string)
		**out = **in
	}
	if in.OrganizationalUnit != nil {
		in, out := &in.OrganizationalUnit, &out.OrganizationalUnit
		*out = new(string)
		**out = **in
	}
	if in.SubjectAlternativeName != nil {
		in, out := &in.SubjectAlternativeName, &out.SubjectAlternativeName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateFiltersParameters.
func (in *CertificateFiltersParameters) DeepCopy() *CertificateFiltersParameters {
	if in == nil {
		return nil
	}
	out := new(CertificateFiltersParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodecServerInitParameters) DeepCopyInto(out *CodecServerInitParameters) {
	*out = *in
	if in.CustomErrorLink != nil {
		in, out := &in.CustomErrorLink, &out.CustomErrorLink
		*out = new(string)
		**out = **in
	}
	if in.CustomErrorMessage != nil {
		in, out := &in.CustomErrorMessage, &out.CustomErrorMessage
		*out = new(string)
		**out = **in
	}
	if in.Endpoint != nil {
		in, out := &in.Endpoint, &out.Endpoint
		*out = new(string)
		**out = **in
	}
	if in.IncludeCrossOriginCredentials != nil {
		in, out := &in.IncludeCrossOriginCredentials, &out.IncludeCrossOriginCredentials
		*out = new(bool)
		**out = **in
	}
	if in.PassAccessToken != nil {
		in, out := &in.PassAccessToken, &out.PassAccessToken
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodecServerInitParameters.
func (in *CodecServerInitParameters) DeepCopy() *CodecServerInitParameters {
	if in == nil {
		return nil
	}
	out := new(CodecServerInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodecServerObservation) DeepCopyInto(out *CodecServerObservation) {
	*out = *in
	if in.CustomErrorLink != nil {
		in, out := &in.CustomErrorLink, &out.CustomErrorLink
		*out = new(string)
		**out = **in
	}
	if in.CustomErrorMessage != nil {
		in, out := &in.CustomErrorMessage, &out.CustomErrorMessage
		*out = new(string)
		**out = **in
	}
	if in.Endpoint != nil {
		in, out := &in.Endpoint, &out.Endpoint
		*out = new(string)
		**out = **in
	}
	if in.IncludeCrossOriginCredentials != nil {
		in, out := &in.IncludeCrossOriginCredentials, &out.IncludeCrossOriginCredentials
		*out = new(bool)
		**out = **in
	}
	if in.PassAccessToken != nil {
		in, out := &in.PassAccessToken, &out.PassAccessToken
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodecServerObservation.
func (in *CodecServerObservation) DeepCopy() *CodecServerObservation {
	if in == nil {
		return nil
	}
	out := new(CodecServerObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodecServerParameters) DeepCopyInto(out *CodecServerParameters) {
	*out = *in
	if in.CustomErrorLink != nil {
		in, out := &in.CustomErrorLink, &out.CustomErrorLink
		*out = new(string)
		**out = **in
	}
	if in.CustomErrorMessage != nil {
		in, out := &in.CustomErrorMessage, &out.CustomErrorMessage
		*out = new(string)
		**out = **in
	}
	if in.Endpoint != nil {
		in, out := &in.Endpoint, &out.Endpoint
		*out = new(string)
		**out = **in
	}
	if in.IncludeCrossOriginCredentials != nil {
		in, out := &in.IncludeCrossOriginCredentials, &out.IncludeCrossOriginCredentials
		*out = new(bool)
		**out = **in
	}
	if in.PassAccessToken != nil {
		in, out := &in.PassAccessToken, &out.PassAccessToken
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodecServerParameters.
func (in *CodecServerParameters) DeepCopy() *CodecServerParameters {
	if in == nil {
		return nil
	}
	out := new(CodecServerParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointsInitParameters) DeepCopyInto(out *EndpointsInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointsInitParameters.
func (in *EndpointsInitParameters) DeepCopy() *EndpointsInitParameters {
	if in == nil {
		return nil
	}
	out := new(EndpointsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointsObservation) DeepCopyInto(out *EndpointsObservation) {
	*out = *in
	if in.GRPCAddress != nil {
		in, out := &in.GRPCAddress, &out.GRPCAddress
		*out = new(string)
		**out = **in
	}
	if in.MtlsGRPCAddress != nil {
		in, out := &in.MtlsGRPCAddress, &out.MtlsGRPCAddress
		*out = new(string)
		**out = **in
	}
	if in.WebAddress != nil {
		in, out := &in.WebAddress, &out.WebAddress
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointsObservation.
func (in *EndpointsObservation) DeepCopy() *EndpointsObservation {
	if in == nil {
		return nil
	}
	out := new(EndpointsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointsParameters) DeepCopyInto(out *EndpointsParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointsParameters.
func (in *EndpointsParameters) DeepCopy() *EndpointsParameters {
	if in == nil {
		return nil
	}
	out := new(EndpointsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FairnessInitParameters) DeepCopyInto(out *FairnessInitParameters) {
	*out = *in
	if in.TaskQueueFairnessEnabled != nil {
		in, out := &in.TaskQueueFairnessEnabled, &out.TaskQueueFairnessEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FairnessInitParameters.
func (in *FairnessInitParameters) DeepCopy() *FairnessInitParameters {
	if in == nil {
		return nil
	}
	out := new(FairnessInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FairnessObservation) DeepCopyInto(out *FairnessObservation) {
	*out = *in
	if in.TaskQueueFairnessEnabled != nil {
		in, out := &in.TaskQueueFairnessEnabled, &out.TaskQueueFairnessEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FairnessObservation.
func (in *FairnessObservation) DeepCopy() *FairnessObservation {
	if in == nil {
		return nil
	}
	out := new(FairnessObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FairnessParameters) DeepCopyInto(out *FairnessParameters) {
	*out = *in
	if in.TaskQueueFairnessEnabled != nil {
		in, out := &in.TaskQueueFairnessEnabled, &out.TaskQueueFairnessEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FairnessParameters.
func (in *FairnessParameters) DeepCopy() *FairnessParameters {
	if in == nil {
		return nil
	}
	out := new(FairnessParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Namespace) DeepCopyInto(out *Namespace) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Namespace.
func (in *Namespace) DeepCopy() *Namespace {
	if in == nil {
		return nil
	}
	out := new(Namespace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Namespace) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceInitParameters) DeepCopyInto(out *NamespaceInitParameters) {
	*out = *in
	if in.APIKeyAuth != nil {
		in, out := &in.APIKeyAuth, &out.APIKeyAuth
		*out = new(bool)
		**out = **in
	}
	if in.AcceptedClientCA != nil {
		in, out := &in.AcceptedClientCA, &out.AcceptedClientCA
		*out = new(string)
		**out = **in
	}
	if in.Capacity != nil {
		in, out := &in.Capacity, &out.Capacity
		*out = new(CapacityInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.CertificateFilters != nil {
		in, out := &in.CertificateFilters, &out.CertificateFilters
		*out = make([]CertificateFiltersInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CodecServer != nil {
		in, out := &in.CodecServer, &out.CodecServer
		*out = new(CodecServerInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.ConnectivityRuleIds != nil {
		in, out := &in.ConnectivityRuleIds, &out.ConnectivityRuleIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Fairness != nil {
		in, out := &in.Fairness, &out.Fairness
		*out = new(FairnessInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NamespaceLifecycle != nil {
		in, out := &in.NamespaceLifecycle, &out.NamespaceLifecycle
		*out = new(NamespaceLifecycleInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Regions != nil {
		in, out := &in.Regions, &out.Regions
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RetentionDays != nil {
		in, out := &in.RetentionDays, &out.RetentionDays
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceInitParameters.
func (in *NamespaceInitParameters) DeepCopy() *NamespaceInitParameters {
	if in == nil {
		return nil
	}
	out := new(NamespaceInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceLifecycleInitParameters) DeepCopyInto(out *NamespaceLifecycleInitParameters) {
	*out = *in
	if in.EnableDeleteProtection != nil {
		in, out := &in.EnableDeleteProtection, &out.EnableDeleteProtection
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceLifecycleInitParameters.
func (in *NamespaceLifecycleInitParameters) DeepCopy() *NamespaceLifecycleInitParameters {
	if in == nil {
		return nil
	}
	out := new(NamespaceLifecycleInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceLifecycleObservation) DeepCopyInto(out *NamespaceLifecycleObservation) {
	*out = *in
	if in.EnableDeleteProtection != nil {
		in, out := &in.EnableDeleteProtection, &out.EnableDeleteProtection
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceLifecycleObservation.
func (in *NamespaceLifecycleObservation) DeepCopy() *NamespaceLifecycleObservation {
	if in == nil {
		return nil
	}
	out := new(NamespaceLifecycleObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceLifecycleParameters) DeepCopyInto(out *NamespaceLifecycleParameters) {
	*out = *in
	if in.EnableDeleteProtection != nil {
		in, out := &in.EnableDeleteProtection, &out.EnableDeleteProtection
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceLifecycleParameters.
func (in *NamespaceLifecycleParameters) DeepCopy() *NamespaceLifecycleParameters {
	if in == nil {
		return nil
	}
	out := new(NamespaceLifecycleParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceList) DeepCopyInto(out *NamespaceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Namespace, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceList.
func (in *NamespaceList) DeepCopy() *NamespaceList {
	if in == nil {
		return nil
	}
	out := new(NamespaceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NamespaceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceObservation) DeepCopyInto(out *NamespaceObservation) {
	*out = *in
	if in.APIKeyAuth != nil {
		in, out := &in.APIKeyAuth, &out.APIKeyAuth
		*out = new(bool)
		**out = **in
	}
	if in.AcceptedClientCA != nil {
		in, out := &in.AcceptedClientCA, &out.AcceptedClientCA
		*out = new(string)
		**out = **in
	}
	if in.Capacity != nil {
		in, out := &in.Capacity, &out.Capacity
		*out = new(CapacityObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.CertificateFilters != nil {
		in, out := &in.CertificateFilters, &out.CertificateFilters
		*out = make([]CertificateFiltersObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CodecServer != nil {
		in, out := &in.CodecServer, &out.CodecServer
		*out = new(CodecServerObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.ConnectivityRuleIds != nil {
		in, out := &in.ConnectivityRuleIds, &out.ConnectivityRuleIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = new(EndpointsObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Fairness != nil {
		in, out := &in.Fairness, &out.Fairness
		*out = new(FairnessObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NamespaceLifecycle != nil {
		in, out := &in.NamespaceLifecycle, &out.NamespaceLifecycle
		*out = new(NamespaceLifecycleObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Regions != nil {
		in, out := &in.Regions, &out.Regions
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RetentionDays != nil {
		in, out := &in.RetentionDays, &out.RetentionDays
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceObservation.
func (in *NamespaceObservation) DeepCopy() *NamespaceObservation {
	if in == nil {
		return nil
	}
	out := new(NamespaceObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceParameters) DeepCopyInto(out *NamespaceParameters) {
	*out = *in
	if in.APIKeyAuth != nil {
		in, out := &in.APIKeyAuth, &out.APIKeyAuth
		*out = new(bool)
		**out = **in
	}
	if in.AcceptedClientCA != nil {
		in, out := &in.AcceptedClientCA, &out.AcceptedClientCA
		*out = new(string)
		**out = **in
	}
	if in.Capacity != nil {
		in, out := &in.Capacity, &out.Capacity
		*out = new(CapacityParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.CertificateFilters != nil {
		in, out := &in.CertificateFilters, &out.CertificateFilters
		*out = make([]CertificateFiltersParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CodecServer != nil {
		in, out := &in.CodecServer, &out.CodecServer
		*out = new(CodecServerParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.ConnectivityRuleIds != nil {
		in, out := &in.ConnectivityRuleIds, &out.ConnectivityRuleIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Fairness != nil {
		in, out := &in.Fairness, &out.Fairness
		*out = new(FairnessParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NamespaceLifecycle != nil {
		in, out := &in.NamespaceLifecycle, &out.NamespaceLifecycle
		*out = new(NamespaceLifecycleParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Regions != nil {
		in, out := &in.Regions, &out.Regions
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RetentionDays != nil {
		in, out := &in.RetentionDays, &out.RetentionDays
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceParameters.
func (in *NamespaceParameters) DeepCopy() *NamespaceParameters {
	if in == nil {
		return nil
	}
	out := new(NamespaceParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceSpec) DeepCopyInto(out *NamespaceSpec) {
	*out = *in
	in.ClusterManagedResourceSpec.DeepCopyInto(&out.ClusterManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceSpec.
func (in *NamespaceSpec) DeepCopy() *NamespaceSpec {
	if in == nil {
		return nil
	}
	out := new(NamespaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceStatus) DeepCopyInto(out *NamespaceStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceStatus.
func (in *NamespaceStatus) DeepCopy() *NamespaceStatus {
	if in == nil {
		return nil
	}
	out := new(NamespaceStatus)
	in.DeepCopyInto(out)
	return out
}
