// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type CapacityInitParameters struct {

	// (String) The mode of the capacity configuration. Must be one of 'provisioned' or 'on_demand'.
	// The mode of the capacity configuration. Must be one of 'provisioned' or 'on_demand'.
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// (Number) The value of the capacity configuration. Must be set when mode is 'provisioned'.
	// The value of the capacity configuration. Must be set when mode is 'provisioned'.
	Value *float64 `json:"value,omitempty" tf:"value,omitempty"`
}

type CapacityObservation struct {

	// (String) The mode of the capacity configuration. Must be one of 'provisioned' or 'on_demand'.
	// The mode of the capacity configuration. Must be one of 'provisioned' or 'on_demand'.
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// (Number) The value of the capacity configuration. Must be set when mode is 'provisioned'.
	// The value of the capacity configuration. Must be set when mode is 'provisioned'.
	Value *float64 `json:"value,omitempty" tf:"value,omitempty"`
}

type CapacityParameters struct {

	// (String) The mode of the capacity configuration. Must be one of 'provisioned' or 'on_demand'.
	// The mode of the capacity configuration. Must be one of 'provisioned' or 'on_demand'.
	// +kubebuilder:validation:Optional
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// (Number) The value of the capacity configuration. Must be set when mode is 'provisioned'.
	// The value of the capacity configuration. Must be set when mode is 'provisioned'.
	// +kubebuilder:validation:Optional
	Value *float64 `json:"value,omitempty" tf:"value,omitempty"`
}

type CertificateFiltersInitParameters struct {

	// (String) The certificate's common name.
	// The certificate's common name.
	CommonName *string `json:"commonName,omitempty" tf:"common_name,omitempty"`

	// (String) The certificate's organization.
	// The certificate's organization.
	Organization *string `json:"organization,omitempty" tf:"organization,omitempty"`

	// (String) The certificate's organizational unit.
	// The certificate's organizational unit.
	OrganizationalUnit *string `json:"organizationalUnit,omitempty" tf:"organizational_unit,omitempty"`

	// (String) The certificate's subject alternative name (or SAN).
	// The certificate's subject alternative name (or SAN).
	SubjectAlternativeName *string `json:"subjectAlternativeName,omitempty" tf:"subject_alternative_name,omitempty"`
}

type CertificateFiltersObservation struct {

	// (String) The certificate's common name.
	// The certificate's common name.
	CommonName *string `json:"commonName,omitempty" tf:"common_name,omitempty"`

	// (String) The certificate's organization.
	// The certificate's organization.
	Organization *string `json:"organization,omitempty" tf:"organization,omitempty"`

	// (String) The certificate's organizational unit.
	// The certificate's organizational unit.
	OrganizationalUnit *string `json:"organizationalUnit,omitempty" tf:"organizational_unit,omitempty"`

	// (String) The certificate's subject alternative name (or SAN).
	// The certificate's subject alternative name (or SAN).
	SubjectAlternativeName *string `json:"subjectAlternativeName,omitempty" tf:"subject_alternative_name,omitempty"`
}

type CertificateFiltersParameters struct {

	// (String) The certificate's common name.
	// The certificate's common name.
	// +kubebuilder:validation:Optional
	CommonName *string `json:"commonName,omitempty" tf:"common_name,omitempty"`

	// (String) The certificate's organization.
	// The certificate's organization.
	// +kubebuilder:validation:Optional
	Organization *string `json:"organization,omitempty" tf:"organization,omitempty"`

	// (String) The certificate's organizational unit.
	// The certificate's organizational unit.
	// +kubebuilder:validation:Optional
	OrganizationalUnit *string `json:"organizationalUnit,omitempty" tf:"organizational_unit,omitempty"`

	// (String) The certificate's subject alternative name (or SAN).
	// The certificate's subject alternative name (or SAN).
	// +kubebuilder:validation:Optional
	SubjectAlternativeName *string `json:"subjectAlternativeName,omitempty" tf:"subject_alternative_name,omitempty"`
}

type CodecServerInitParameters struct {

	// (String) A link displayed alongside the custom error message for the codec server.
	// A link displayed alongside the custom error message for the codec server.
	CustomErrorLink *string `json:"customErrorLink,omitempty" tf:"custom_error_link,omitempty"`

	// (String) A custom error message to display when the codec server returns an error.
	// A custom error message to display when the codec server returns an error.
	CustomErrorMessage *string `json:"customErrorMessage,omitempty" tf:"custom_error_message,omitempty"`

	// (String) The endpoint of the codec server. Must begin with "https".
	// The endpoint of the codec server. Must begin with "https".
	Endpoint *string `json:"endpoint,omitempty" tf:"endpoint,omitempty"`

	// origin credentials in requests to the codec server.
	// If true, Temporal Cloud will include cross-origin credentials in requests to the codec server.
	IncludeCrossOriginCredentials *bool `json:"includeCrossOriginCredentials,omitempty" tf:"include_cross_origin_credentials,omitempty"`

	// (Boolean) If true, Temporal Cloud will pass the access token to the codec server upon each request.
	// If true, Temporal Cloud will pass the access token to the codec server upon each request.
	PassAccessToken *bool `json:"passAccessToken,omitempty" tf:"pass_access_token,omitempty"`
}

type CodecServerObservation struct {

	// (String) A link displayed alongside the custom error message for the codec server.
	// A link displayed alongside the custom error message for the codec server.
	CustomErrorLink *string `json:"customErrorLink,omitempty" tf:"custom_error_link,omitempty"`

	// (String) A custom error message to display when the codec server returns an error.
	// A custom error message to display when the codec server returns an error.
	CustomErrorMessage *string `json:"customErrorMessage,omitempty" tf:"custom_error_message,omitempty"`

	// (String) The endpoint of the codec server. Must begin with "https".
	// The endpoint of the codec server. Must begin with "https".
	Endpoint *string `json:"endpoint,omitempty" tf:"endpoint,omitempty"`

	// origin credentials in requests to the codec server.
	// If true, Temporal Cloud will include cross-origin credentials in requests to the codec server.
	IncludeCrossOriginCredentials *bool `json:"includeCrossOriginCredentials,omitempty" tf:"include_cross_origin_credentials,omitempty"`

	// (Boolean) If true, Temporal Cloud will pass the access token to the codec server upon each request.
	// If true, Temporal Cloud will pass the access token to the codec server upon each request.
	PassAccessToken *bool `json:"passAccessToken,omitempty" tf:"pass_access_token,omitempty"`
}

type CodecServerParameters struct {

	// (String) A link displayed alongside the custom error message for the codec server.
	// A link displayed alongside the custom error message for the codec server.
	// +kubebuilder:validation:Optional
	CustomErrorLink *string `json:"customErrorLink,omitempty" tf:"custom_error_link,omitempty"`

	// (String) A custom error message to display when the codec server returns an error.
	// A custom error message to display when the codec server returns an error.
	// +kubebuilder:validation:Optional
	CustomErrorMessage *string `json:"customErrorMessage,omitempty" tf:"custom_error_message,omitempty"`

	// (String) The endpoint of the codec server. Must begin with "https".
	// The endpoint of the codec server. Must begin with "https".
	// +kubebuilder:validation:Optional
	Endpoint *string `json:"endpoint" tf:"endpoint,omitempty"`

	// origin credentials in requests to the codec server.
	// If true, Temporal Cloud will include cross-origin credentials in requests to the codec server.
	// +kubebuilder:validation:Optional
	IncludeCrossOriginCredentials *bool `json:"includeCrossOriginCredentials,omitempty" tf:"include_cross_origin_credentials,omitempty"`

	// (Boolean) If true, Temporal Cloud will pass the access token to the codec server upon each request.
	// If true, Temporal Cloud will pass the access token to the codec server upon each request.
	// +kubebuilder:validation:Optional
	PassAccessToken *bool `json:"passAccessToken,omitempty" tf:"pass_access_token,omitempty"`
}

type EndpointsInitParameters struct {
}

type EndpointsObservation struct {

	// (String) The gRPC address for API key client connections (may be empty if API keys are disabled).
	// The gRPC address for API key client connections (may be empty if API keys are disabled).
	GRPCAddress *string `json:"grpcAddress,omitempty" tf:"grpc_address,omitempty"`

	// (String) The gRPC address for mTLS client connections (may be empty if mTLS is disabled).
	// The gRPC address for mTLS client connections (may be empty if mTLS is disabled).
	MtlsGRPCAddress *string `json:"mtlsGrpcAddress,omitempty" tf:"mtls_grpc_address,omitempty"`

	// (String) The address in the Temporal Cloud Web UI for the namespace
	// The address in the Temporal Cloud Web UI for the namespace
	WebAddress *string `json:"webAddress,omitempty" tf:"web_address,omitempty"`
}

type EndpointsParameters struct {
}

type FairnessInitParameters struct {

	// (Boolean) Flag to enable task queue fairness for the namespace. Defaults to disabled.
	// Flag to enable task queue fairness for the namespace. Defaults to disabled.
	TaskQueueFairnessEnabled *bool `json:"taskQueueFairnessEnabled,omitempty" tf:"task_queue_fairness_enabled,omitempty"`
}

type FairnessObservation struct {

	// (Boolean) Flag to enable task queue fairness for the namespace. Defaults to disabled.
	// Flag to enable task queue fairness for the namespace. Defaults to disabled.
	TaskQueueFairnessEnabled *bool `json:"taskQueueFairnessEnabled,omitempty" tf:"task_queue_fairness_enabled,omitempty"`
}

type FairnessParameters struct {

	// (Boolean) Flag to enable task queue fairness for the namespace. Defaults to disabled.
	// Flag to enable task queue fairness for the namespace. Defaults to disabled.
	// +kubebuilder:validation:Optional
	TaskQueueFairnessEnabled *bool `json:"taskQueueFairnessEnabled,omitempty" tf:"task_queue_fairness_enabled,omitempty"`
}

type NamespaceInitParameters struct {

	// (Boolean) If true, Temporal Cloud will enable API key authentication for this namespace.
	// If true, Temporal Cloud will enable API key authentication for this namespace.
	APIKeyAuth *bool `json:"apiKeyAuth,omitempty" tf:"api_key_auth,omitempty"`

	// encoded CA cert in PEM format that clients use when authenticating with Temporal Cloud. This is a required field when a Namespace uses mTLS authentication.
	// The Base64-encoded CA cert in PEM format that clients use when authenticating with Temporal Cloud. This is a required field when a Namespace uses mTLS authentication.
	AcceptedClientCA *string `json:"acceptedClientCa,omitempty" tf:"accepted_client_ca,omitempty"`

	// (Attributes) The capacity configuration for the namespace. (see below for nested schema)
	Capacity *CapacityInitParameters `json:"capacity,omitempty" tf:"capacity,omitempty"`

	// (Attributes List) A list of filters to apply to client certificates when initiating a connection Temporal Cloud. If present, connections will only be allowed from client certificates whose distinguished name properties match at least one of the filters. Empty lists are not allowed, omit the attribute instead. (see below for nested schema)
	CertificateFilters []CertificateFiltersInitParameters `json:"certificateFilters,omitempty" tf:"certificate_filters,omitempty"`

	// (Attributes) A codec server is used by the Temporal Cloud UI to decode payloads for all users interacting with this namespace, even if the workflow history itself is encrypted. (see below for nested schema)
	CodecServer *CodecServerInitParameters `json:"codecServer,omitempty" tf:"codec_server,omitempty"`

	// (Set of String) The IDs of the connectivity rules for this namespace.
	// The IDs of the connectivity rules for this namespace.
	// +listType=set
	ConnectivityRuleIds []*string `json:"connectivityRuleIds,omitempty" tf:"connectivity_rule_ids,omitempty"`

	// (Attributes) The fairness configuration for the namespace. (see below for nested schema)
	Fairness *FairnessInitParameters `json:"fairness,omitempty" tf:"fairness,omitempty"`

	// 64 characters, start with a letter, contain only lowercase letters, numbers, and hyphens, and not end with a hyphen.
	// The name of the namespace. Must be 2-64 characters, start with a letter, contain only lowercase letters, numbers, and hyphens, and not end with a hyphen.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes) The lifecycle configuration for the namespace. This controls settings like delete protection within Temporal Cloud. (see below for nested schema)
	NamespaceLifecycle *NamespaceLifecycleInitParameters `json:"namespaceLifecycle,omitempty" tf:"namespace_lifecycle,omitempty"`

	// us-east-1, not us-east-1). If two regions are specified, the namespace will be replicated across them in a high availability (HA) configuration. Same-region, multi-region, and multi-cloud HA namespaces are supported. Please note that changing, adding, or removing regions for an existing namespace is not currently supported and the provider will throw an error. For HA namespaces the provider will ignore order changes on regions, which can happen if the namespace fails over.
	// The list of regions where this namespace is available. Must be one or two regions. See https://docs.temporal.io/cloud/regions for a list of available regions and HA options. Note that regions are prefixed with the cloud provider (aws-us-east-1, not us-east-1). If two regions are specified, the namespace will be replicated across them in a high availability (HA) configuration. Same-region, multi-region, and multi-cloud HA namespaces are supported. Please note that changing, adding, or removing regions for an existing namespace is not currently supported and the provider will throw an error. For HA namespaces the provider will ignore order changes on regions, which can happen if the namespace fails over.
	Regions []*string `json:"regions,omitempty" tf:"regions,omitempty"`

	// (Number) The number of days to retain workflow history. Any changes to the retention period will be applied to all new running workflows.
	// The number of days to retain workflow history. Any changes to the retention period will be applied to all new running workflows.
	RetentionDays *float64 `json:"retentionDays,omitempty" tf:"retention_days,omitempty"`
}

type NamespaceLifecycleInitParameters struct {

	// (Boolean) If true, the namespace cannot be deleted. This is a safeguard against accidental deletion. To delete a namespace with this option enabled, you must first set it to false.
	// If true, the namespace cannot be deleted. This is a safeguard against accidental deletion. To delete a namespace with this option enabled, you must first set it to false.
	EnableDeleteProtection *bool `json:"enableDeleteProtection,omitempty" tf:"enable_delete_protection,omitempty"`
}

type NamespaceLifecycleObservation struct {

	// (Boolean) If true, the namespace cannot be deleted. This is a safeguard against accidental deletion. To delete a namespace with this option enabled, you must first set it to false.
	// If true, the namespace cannot be deleted. This is a safeguard against accidental deletion. To delete a namespace with this option enabled, you must first set it to false.
	EnableDeleteProtection *bool `json:"enableDeleteProtection,omitempty" tf:"enable_delete_protection,omitempty"`
}

type NamespaceLifecycleParameters struct {

	// (Boolean) If true, the namespace cannot be deleted. This is a safeguard against accidental deletion. To delete a namespace with this option enabled, you must first set it to false.
	// If true, the namespace cannot be deleted. This is a safeguard against accidental deletion. To delete a namespace with this option enabled, you must first set it to false.
	// +kubebuilder:validation:Optional
	EnableDeleteProtection *bool `json:"enableDeleteProtection,omitempty" tf:"enable_delete_protection,omitempty"`
}

type NamespaceObservation struct {

	// (Boolean) If true, Temporal Cloud will enable API key authentication for this namespace.
	// If true, Temporal Cloud will enable API key authentication for this namespace.
	APIKeyAuth *bool `json:"apiKeyAuth,omitempty" tf:"api_key_auth,omitempty"`

	// encoded CA cert in PEM format that clients use when authenticating with Temporal Cloud. This is a required field when a Namespace uses mTLS authentication.
	// The Base64-encoded CA cert in PEM format that clients use when authenticating with Temporal Cloud. This is a required field when a Namespace uses mTLS authentication.
	AcceptedClientCA *string `json:"acceptedClientCa,omitempty" tf:"accepted_client_ca,omitempty"`

	// (Attributes) The capacity configuration for the namespace. (see below for nested schema)
	Capacity *CapacityObservation `json:"capacity,omitempty" tf:"capacity,omitempty"`

	// (Attributes List) A list of filters to apply to client certificates when initiating a connection Temporal Cloud. If present, connections will only be allowed from client certificates whose distinguished name properties match at least one of the filters. Empty lists are not allowed, omit the attribute instead. (see below for nested schema)
	CertificateFilters []CertificateFiltersObservation `json:"certificateFilters,omitempty" tf:"certificate_filters,omitempty"`

	// (Attributes) A codec server is used by the Temporal Cloud UI to decode payloads for all users interacting with this namespace, even if the workflow history itself is encrypted. (see below for nested schema)
	CodecServer *CodecServerObservation `json:"codecServer,omitempty" tf:"codec_server,omitempty"`

	// (Set of String) The IDs of the connectivity rules for this namespace.
	// The IDs of the connectivity rules for this namespace.
	// +listType=set
	ConnectivityRuleIds []*string `json:"connectivityRuleIds,omitempty" tf:"connectivity_rule_ids,omitempty"`

	// (Attributes) The endpoints for the namespace. (see below for nested schema)
	Endpoints *EndpointsObservation `json:"endpoints,omitempty" tf:"endpoints,omitempty"`

	// (Attributes) The fairness configuration for the namespace. (see below for nested schema)
	Fairness *FairnessObservation `json:"fairness,omitempty" tf:"fairness,omitempty"`

	// (String) The unique identifier of the namespace across all Temporal Cloud tenants.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// 64 characters, start with a letter, contain only lowercase letters, numbers, and hyphens, and not end with a hyphen.
	// The name of the namespace. Must be 2-64 characters, start with a letter, contain only lowercase letters, numbers, and hyphens, and not end with a hyphen.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes) The lifecycle configuration for the namespace. This controls settings like delete protection within Temporal Cloud. (see below for nested schema)
	NamespaceLifecycle *NamespaceLifecycleObservation `json:"namespaceLifecycle,omitempty" tf:"namespace_lifecycle,omitempty"`

	// us-east-1, not us-east-1). If two regions are specified, the namespace will be replicated across them in a high availability (HA) configuration. Same-region, multi-region, and multi-cloud HA namespaces are supported. Please note that changing, adding, or removing regions for an existing namespace is not currently supported and the provider will throw an error. For HA namespaces the provider will ignore order changes on regions, which can happen if the namespace fails over.
	// The list of regions where this namespace is available. Must be one or two regions. See https://docs.temporal.io/cloud/regions for a list of available regions and HA options. Note that regions are prefixed with the cloud provider (aws-us-east-1, not us-east-1). If two regions are specified, the namespace will be replicated across them in a high availability (HA) configuration. Same-region, multi-region, and multi-cloud HA namespaces are supported. Please note that changing, adding, or removing regions for an existing namespace is not currently supported and the provider will throw an error. For HA namespaces the provider will ignore order changes on regions, which can happen if the namespace fails over.
	Regions []*string `json:"regions,omitempty" tf:"regions,omitempty"`

	// (Number) The number of days to retain workflow history. Any changes to the retention period will be applied to all new running workflows.
	// The number of days to retain workflow history. Any changes to the retention period will be applied to all new running workflows.
	RetentionDays *float64 `json:"retentionDays,omitempty" tf:"retention_days,omitempty"`
}

type NamespaceParameters struct {

	// (Boolean) If true, Temporal Cloud will enable API key authentication for this namespace.
	// If true, Temporal Cloud will enable API key authentication for this namespace.
	// +kubebuilder:validation:Optional
	APIKeyAuth *bool `json:"apiKeyAuth,omitempty" tf:"api_key_auth,omitempty"`

	// encoded CA cert in PEM format that clients use when authenticating with Temporal Cloud. This is a required field when a Namespace uses mTLS authentication.
	// The Base64-encoded CA cert in PEM format that clients use when authenticating with Temporal Cloud. This is a required field when a Namespace uses mTLS authentication.
	// +kubebuilder:validation:Optional
	AcceptedClientCA *string `json:"acceptedClientCa,omitempty" tf:"accepted_client_ca,omitempty"`

	// (Attributes) The capacity configuration for the namespace. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Capacity *CapacityParameters `json:"capacity,omitempty" tf:"capacity,omitempty"`

	// (Attributes List) A list of filters to apply to client certificates when initiating a connection Temporal Cloud. If present, connections will only be allowed from client certificates whose distinguished name properties match at least one of the filters. Empty lists are not allowed, omit the attribute instead. (see below for nested schema)
	// +kubebuilder:validation:Optional
	CertificateFilters []CertificateFiltersParameters `json:"certificateFilters,omitempty" tf:"certificate_filters,omitempty"`

	// (Attributes) A codec server is used by the Temporal Cloud UI to decode payloads for all users interacting with this namespace, even if the workflow history itself is encrypted. (see below for nested schema)
	// +kubebuilder:validation:Optional
	CodecServer *CodecServerParameters `json:"codecServer,omitempty" tf:"codec_server,omitempty"`

	// (Set of String) The IDs of the connectivity rules for this namespace.
	// The IDs of the connectivity rules for this namespace.
	// +kubebuilder:validation:Optional
	// +listType=set
	ConnectivityRuleIds []*string `json:"connectivityRuleIds,omitempty" tf:"connectivity_rule_ids,omitempty"`

	// (Attributes) The fairness configuration for the namespace. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Fairness *FairnessParameters `json:"fairness,omitempty" tf:"fairness,omitempty"`

	// 64 characters, start with a letter, contain only lowercase letters, numbers, and hyphens, and not end with a hyphen.
	// The name of the namespace. Must be 2-64 characters, start with a letter, contain only lowercase letters, numbers, and hyphens, and not end with a hyphen.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes) The lifecycle configuration for the namespace. This controls settings like delete protection within Temporal Cloud. (see below for nested schema)
	// +kubebuilder:validation:Optional
	NamespaceLifecycle *NamespaceLifecycleParameters `json:"namespaceLifecycle,omitempty" tf:"namespace_lifecycle,omitempty"`

	// us-east-1, not us-east-1). If two regions are specified, the namespace will be replicated across them in a high availability (HA) configuration. Same-region, multi-region, and multi-cloud HA namespaces are supported. Please note that changing, adding, or removing regions for an existing namespace is not currently supported and the provider will throw an error. For HA namespaces the provider will ignore order changes on regions, which can happen if the namespace fails over.
	// The list of regions where this namespace is available. Must be one or two regions. See https://docs.temporal.io/cloud/regions for a list of available regions and HA options. Note that regions are prefixed with the cloud provider (aws-us-east-1, not us-east-1). If two regions are specified, the namespace will be replicated across them in a high availability (HA) configuration. Same-region, multi-region, and multi-cloud HA namespaces are supported. Please note that changing, adding, or removing regions for an existing namespace is not currently supported and the provider will throw an error. For HA namespaces the provider will ignore order changes on regions, which can happen if the namespace fails over.
	// +kubebuilder:validation:Optional
	Regions []*string `json:"regions,omitempty" tf:"regions,omitempty"`

	// (Number) The number of days to retain workflow history. Any changes to the retention period will be applied to all new running workflows.
	// The number of days to retain workflow history. Any changes to the retention period will be applied to all new running workflows.
	// +kubebuilder:validation:Optional
	RetentionDays *float64 `json:"retentionDays,omitempty" tf:"retention_days,omitempty"`
}

// NamespaceSpec defines the desired state of Namespace
type NamespaceSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   NamespaceParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider NamespaceInitParameters `json:"initProvider,omitempty"`
}

// NamespaceStatus defines the observed state of Namespace.
type NamespaceStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               NamespaceObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Namespace is the Schema for the Namespaces API. Provisions a Temporal Cloud namespace. Regions available in Temporal Cloud: https://docs.temporal.io/cloud/regions. Note that regions are prefixed with the cloud provider (aws-us-east-1, not us-east-1)
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,temporalcloud}
type Namespace struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.regions) || (has(self.initProvider) && has(self.initProvider.regions))",message="spec.forProvider.regions is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.retentionDays) || (has(self.initProvider) && has(self.initProvider.retentionDays))",message="spec.forProvider.retentionDays is a required parameter"
	Spec   NamespaceSpec   `json:"spec"`
	Status NamespaceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NamespaceList contains a list of Namespaces
type NamespaceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Namespace `json:"items"`
}

// Repository type metadata.
var (
	Namespace_Kind             = "Namespace"
	Namespace_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Namespace_Kind}.String()
	Namespace_KindAPIVersion   = Namespace_Kind + "." + CRDGroupVersion.String()
	Namespace_GroupVersionKind = CRDGroupVersion.WithKind(Namespace_Kind)
)

func init() {
	SchemeBuilder.Register(&Namespace{}, &NamespaceList{})
}
