apiVersion: v1
kind: Secret
metadata:
  name: temporal-cloud-creds
  namespace: crossplane-system
type: Opaque
stringData:
  credentials: |
    {
      "api_key": "replace-with-temporal-cloud-api-key"
    }
---
apiVersion: temporalcloud.bitovi.com/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      name: temporal-cloud-creds
      namespace: crossplane-system
      key: credentials
---
apiVersion: namespace.temporalcloud.bitovi.com/v1alpha1
kind: Namespace
metadata:
  name: example-dev
spec:
  forProvider:
    name: example-dev
    regions:
      - aws-us-east-1
    retentionDays: 7
    apiKeyAuth: true
  providerConfigRef:
    name: default
  managementPolicies:
    - Observe
    - Create
    - Update
    - LateInitialize
